# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'AIUniversalAssistant' do
  # 使用动态框架（Ads-CN 需要 xcframework 支持）
  use_frameworks! :linkage => :static
  
  # Pods for AIUniversalAssistant
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'Masonry'
    
  # 穿山甲广告SDK (国内版本)
  # 注意：如果 AIUA_AD_ENABLED 设置为 0（模拟器开发时），请注释掉下面这行以避免链接错误
  # 需要启用时，取消注释并运行 pod install
    pod 'Ads-CN'
    # 如果是海外版本，使用: pod 'Ads-Global'
end

# 解决Pods代码签名问题
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # 禁用Pods的代码签名
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
      
      # 设置最低部署目标（避免警告）
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
