# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'AIUniversalAssistant' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for AIUniversalAssistant
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'Masonry'
    
  # 穿山甲广告SDK (国内版本)
    pod 'Ads-CN'
    # 如果是海外版本，使用: pod 'Ads-Global'
end
